namespace Nxt.UI;

/// <summary>
/// Strings owned by the shared components (settings shell, AI chat, toasts, banners).
/// App-specific copy stays in each app. Falls back to English, then the key itself.
/// </summary>
public sealed class NxtText
{
    private readonly INxtLocale _locale;

    public NxtText(INxtLocale locale) => _locale = locale;

    public string this[string key] =>
        (Strings.TryGetValue(_locale.Language, out var table) && table.TryGetValue(key, out var value)) ? value
        : Strings["en"].TryGetValue(key, out var en) ? en
        : key;

    public string T(string key, params object[] args) => string.Format(this[key], args);

    private static readonly Dictionary<string, Dictionary<string, string>> Strings = new()
    {
        ["ar"] = new()
        {
            ["settings_title"] = "الإعدادات",
            ["settings_subtitle"] = "خصّص التطبيق كما يناسبك",
            ["lang_title"] = "اللغة",
            ["lang_desc"] = "اختر لغة الواجهة.",
            ["theme_title"] = "المظهر",
            ["theme_desc"] = "فاتح أو داكن أو حسب إعدادات جهازك.",
            ["theme_system"] = "تلقائي",
            ["theme_light"] = "فاتح",
            ["theme_dark"] = "داكن",
            ["ai_title"] = "المساعد الذكي",
            ["ai_desc"] = "يعمل المساعد بمفتاح Gemini الخاص بك. يُحفظ المفتاح على هذا الجهاز فقط.",
            ["ai_key_label"] = "مفتاح Gemini API",
            ["ai_key_placeholder"] = "الصق المفتاح هنا",
            ["ai_key_link"] = "احصل على مفتاح مجاني ↗",
            ["ai_model_label"] = "النموذج",
            ["ai_refresh_models"] = "تحديث قائمة النماذج",
            ["ai_save"] = "حفظ",
            ["ai_saved"] = "تم حفظ إعدادات المساعد.",
            ["ai_no_models"] = "تعذّر جلب النماذج. تحقق من المفتاح.",
            ["install_title"] = "تثبيت التطبيق",
            ["install_desc"] = "أضف التطبيق إلى الشاشة الرئيسية ليعمل كتطبيق كامل.",
            ["install_link"] = "طريقة التثبيت",
            ["install_steps"] = "على iPhone: زر المشاركة ← «إضافة إلى الشاشة الرئيسية». على Android: قائمة المتصفح ⋮ ← «تثبيت التطبيق».",
            ["about_title"] = "حول التطبيق",
            ["about_version"] = "الإصدار {0}",
            ["about_dev"] = "تطوير رامي الخطيب ↗",
            ["about_more_apps"] = "تطبيقات أخرى من العائلة",
            ["ai_go_settings"] = "اذهب إلى الإعدادات",
            ["ai_no_key"] = "أضف مفتاح Gemini في الإعدادات لتفعيل المساعد.",
            ["ai_thinking"] = "أفكّر…",
            ["ai_send"] = "إرسال",
            ["ai_mic"] = "إملاء صوتي",
            ["listening"] = "أستمع…",
            ["mic_stop"] = "إيقاف التسجيل",
            ["mic_failed"] = "تعذّر تشغيل الميكروفون.",
            ["mic_denied"] = "لم يُسمح باستخدام الميكروفون.",
            ["ai_placeholder"] = "اكتب طلبك…",
            ["ai_empty"] = "كيف يمكنني مساعدتك؟",
            ["update_available"] = "يتوفر إصدار جديد.",
            ["update_refresh"] = "تحديث",
            ["dismiss"] = "إغلاق",
            ["back"] = "السابق",
            ["next"] = "التالي",
            ["start"] = "ابدأ",
            ["step"] = "الخطوة {0} من {1}",
            ["copied"] = "تم النسخ.",
        },
        ["en"] = new()
        {
            ["settings_title"] = "Settings",
            ["settings_subtitle"] = "Make the app yours",
            ["lang_title"] = "Language",
            ["lang_desc"] = "Choose the interface language.",
            ["theme_title"] = "Appearance",
            ["theme_desc"] = "Light, dark, or follow your device.",
            ["theme_system"] = "System",
            ["theme_light"] = "Light",
            ["theme_dark"] = "Dark",
            ["ai_title"] = "AI assistant",
            ["ai_desc"] = "The assistant runs on your own Gemini key. It is stored on this device only.",
            ["ai_key_label"] = "Gemini API key",
            ["ai_key_placeholder"] = "Paste your key",
            ["ai_key_link"] = "Get a free key ↗",
            ["ai_model_label"] = "Model",
            ["ai_refresh_models"] = "Refresh model list",
            ["ai_save"] = "Save",
            ["ai_saved"] = "Assistant settings saved.",
            ["ai_no_models"] = "Couldn't load models. Check your key.",
            ["install_title"] = "Install the app",
            ["install_desc"] = "Add it to your home screen so it opens like a native app.",
            ["install_link"] = "How to install",
            ["install_steps"] = "iPhone: Share button → \"Add to Home Screen\". Android: browser menu ⋮ → \"Install app\".",
            ["about_title"] = "About",
            ["about_version"] = "Version {0}",
            ["about_dev"] = "Made by Rami Alkhateeb ↗",
            ["about_more_apps"] = "More apps in the family",
            ["ai_go_settings"] = "Open Settings",
            ["ai_no_key"] = "Add a Gemini key in Settings to turn on the assistant.",
            ["ai_thinking"] = "Thinking…",
            ["ai_send"] = "Send",
            ["ai_mic"] = "Dictate",
            ["listening"] = "Listening…",
            ["mic_stop"] = "Stop recording",
            ["mic_failed"] = "Couldn't start the microphone.",
            ["mic_denied"] = "Microphone permission was denied.",
            ["ai_placeholder"] = "Type your request…",
            ["ai_empty"] = "How can I help?",
            ["update_available"] = "A new version is available.",
            ["update_refresh"] = "Refresh",
            ["dismiss"] = "Dismiss",
            ["back"] = "Back",
            ["next"] = "Next",
            ["start"] = "Start",
            ["step"] = "Step {0} of {1}",
            ["copied"] = "Copied.",
        },
        ["de"] = new()
        {
            ["settings_title"] = "Einstellungen",
            ["settings_subtitle"] = "Passe die App an",
            ["lang_title"] = "Sprache",
            ["lang_desc"] = "Wähle die Sprache der Oberfläche.",
            ["theme_title"] = "Darstellung",
            ["theme_desc"] = "Hell, dunkel oder wie dein Gerät.",
            ["theme_system"] = "System",
            ["theme_light"] = "Hell",
            ["theme_dark"] = "Dunkel",
            ["ai_title"] = "KI-Assistent",
            ["ai_desc"] = "Der Assistent nutzt deinen eigenen Gemini-Schlüssel. Er bleibt nur auf diesem Gerät.",
            ["ai_key_label"] = "Gemini-API-Schlüssel",
            ["ai_key_placeholder"] = "Schlüssel einfügen",
            ["ai_key_link"] = "Kostenlosen Schlüssel holen ↗",
            ["ai_model_label"] = "Modell",
            ["ai_refresh_models"] = "Modellliste aktualisieren",
            ["ai_save"] = "Speichern",
            ["ai_saved"] = "Assistent-Einstellungen gespeichert.",
            ["ai_no_models"] = "Modelle konnten nicht geladen werden. Prüfe den Schlüssel.",
            ["install_title"] = "App installieren",
            ["install_desc"] = "Zum Startbildschirm hinzufügen, damit sie wie eine echte App startet.",
            ["install_link"] = "So geht's",
            ["install_steps"] = "iPhone: Teilen → „Zum Home-Bildschirm“. Android: Browsermenü ⋮ → „App installieren“.",
            ["about_title"] = "Über",
            ["about_version"] = "Version {0}",
            ["about_dev"] = "Von Rami Alkhateeb ↗",
            ["about_more_apps"] = "Weitere Apps der Familie",
            ["ai_go_settings"] = "Einstellungen öffnen",
            ["ai_no_key"] = "Füge in den Einstellungen einen Gemini-Schlüssel hinzu.",
            ["ai_thinking"] = "Denke nach…",
            ["ai_send"] = "Senden",
            ["ai_mic"] = "Diktieren",
            ["listening"] = "Ich höre zu…",
            ["mic_stop"] = "Aufnahme beenden",
            ["mic_failed"] = "Mikrofon konnte nicht gestartet werden.",
            ["mic_denied"] = "Mikrofonzugriff wurde verweigert.",
            ["ai_placeholder"] = "Schreib deine Anfrage…",
            ["ai_empty"] = "Wie kann ich helfen?",
            ["update_available"] = "Eine neue Version ist verfügbar.",
            ["update_refresh"] = "Aktualisieren",
            ["dismiss"] = "Schließen",
            ["back"] = "Zurück",
            ["next"] = "Weiter",
            ["start"] = "Los geht's",
            ["step"] = "Schritt {0} von {1}",
            ["copied"] = "Kopiert.",
        },
    };
}
